Support for IN clause with tuple sets
ahrefs/sqlgg pull request #17
Opened 2024-08-13 13:15 UTC by jongleb

### Description
This PR adds a support for the WHERE IN with `@tuple` list expression.

Example:

```sql
SELECT `col1`, `col2`
FROM `table1`
WHERE (1, col1, col2, col1 + col1, 6, 11, (@test3 :: Text)) IN @in_ AND col2 > 3;
```

If we need to have a parameter on the left side (before the IN expr), how  `@test3` is, We should specify a type.

2024-08-14 13:39 UTC, jongleb commented on lib/syntax.ml
> +
I could not add a clone just by calling `assign_types` from `resolve_columns`, but I decided not to do it, bypassing
the following function:

```ocaml
and resolve_types env expr =
  let expr = resolve_columns env expr in
  try
    assign_types env expr
  with
    exn ->
      eprintfn "resolve_types failed with %s at:" (Printexc.to_string exn);
      eprintfn "%s" (show_res_expr expr);
      raise exn
```

2024-08-14 13:42 UTC, jongleb commented on lib/syntax.ml
> +  ResTyped of Type.t list | Res of res_expr list
I could not add a clone just by calling `assign_types` from `resolve_columns`, but I decided not to do it, bypassing
the following function:

```ocaml
and resolve_types env expr =
  let expr = resolve_columns env expr in
  try
    assign_types env expr
  with
    exn ->
      eprintfn "resolve_types failed with %s at:" (Printexc.to_string exn);
      eprintfn "%s" (show_res_expr expr);
      raise exn
```

2024-08-15 21:25 UTC, rr0gi requested changes
looks ok

2024-08-15 21:25 UTC, rr0gi commented on src/test.ml
> +  ()
this test is not very useful? it doesn't look at `abc` type

2024-08-15 21:25 UTC, rr0gi commented on lib/syntax.ml
> +            fail "If you need to have a field as parameter in the left part you should specify a type"
i believe everywhere else it is more lax - Any just gets casted to Text when it reaches code gen, lets keep it that way

2024-08-16 06:09 UTC, jongleb commented on src/test.ml
> +  ()
Yes, since we don't consider tuples as literally Sql.type , this is an attempt to check that it at least parse works. I would keep

2024-08-16 07:43 UTC, merged